# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afb2759ba90f085dfc4a93e8b7ff17020e3686bb1eb0086ff72003164f405c5b87880810a159937b34fbf4ca275cdcee54ce33a1131ab52d4a29a6d31d79198a

test:
  secret_key_base: 81f2872ad3bdce04f3aaeffa2e3f69bb56b052701d80321c7f447b93d75b3ea5599720c807fe73bd2500ecd23eee4f0b7890ed45d0876432cc90ad0853b9c6bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
